### ISSUE TITLE
暑修的學分不需列入計算

### ISSUE THREAD

**Issue by 1chooo** [cliffxzx/gpa-calculator-for-ncu#1]
您好！
我也是中央大學的學生，首先非常感謝提供開源的 GPA 計算器，實在造福大眾，不過這邊發現了一個問題那就是：暑修的學分不會一起列入計算。
因此想建議，可以直接跳過暑修的計算，如果我有誤會中央 GPA 的計算方式，還請直接跟我說，非常感謝！

BR,
@1chooo

**Comment by cliffxzx** [comment]
在網路上查到的[中央大學成績表](https://pdc.adm.ncu.edu.tw/Form/form/form02-12t.pdf)說明上的
貳之二之4、貳之四之4等 寫學期分數不計算，但畢業分數會計算

我自己申請紙本 GPA Overall 也和目前擴充功能算的符合
如果拿掉暑修的話就對不上了

我這邊在中文版上測試 擴充功能預設上是有計算暑修的（會有核取方塊在最右邊） 但也可以把他取消勾選
<img width="714" alt="image" src="https://github.com/cliffxzx/gpa-calculator-for-ncu/assets/44764053/ea7340f4-9fa1-4f78-b106-44917d37b690">

不過我也不確定這份說明是否是最新正確的
若有時間等我打到教務處確定後 會再這邊在說明

謝謝🙏

**Comment by 1chooo** [comment]
@cliffxzx 非常感謝您的說明!

**Comment by cliffxzx** [comment]
註冊組回覆詳閱上面貼的 [成績計算說明](https://pdc.adm.ncu.edu.tw/Form/form/form02-12t.pdf)，符合目前計算的方式。

**Comment by 1chooo** [comment]
Thanks @cliffxzx
