### ISSUE TITLE
[Bug] 分數顯示比例錯誤

### ISSUE THREAD

**Issue by 1chooo** [cliffxzx/gpa-calculator-for-ncu#2]
Descriptions
---
以下下的圖為例，`Overall`, `last 60`, `required` 這三個的比例沒有符合實際情形（4.3/4.0 為 100%），不過可以很明顯看到 `last 60`, `required` 這兩項的比例不太對， 4.3 以及 4.0 都有相同問題，尤其 4.0 的部分，GPA 3.5 就用完整個圓形的比例條，可能需要再進行調整，另外可以建議 Extensions 可以新增 `check update` 按鈕，已讓應用程序可以保持最新版本。

一次發了兩個 issue，希望不會造成您太多困難，如有遇到需要討論的情形，非常歡迎直接與我聯絡，可以在我的 GitHub 主頁找到我的相關資訊，最後非常感謝您開源了此項專案造福大家！！！

Screenshots
---
|4.3 | 4.0 |
| -- | --  |
|<img width="250" alt="Screen Shot 2023-08-01 at 12 09 41 AM" src="https://github.com/cliffxzx/gpa-calculator-for-ncu/assets/94162591/044704b7-4305-4a57-86d5-e0b27fa0f195"> |<img width="251" alt="Screen Shot 2023-08-01 at 12 09 48 AM" src="https://github.com/cliffxzx/gpa-calculator-for-ncu/assets/94162591/4ccdd21d-d93d-48c6-bddf-55d5853e4a54"> |

BR,
@1chooo

**Comment by cliffxzx** [comment]
Hello 👋
謝謝你回報問題 並且附上完整訊息
這確實是一個 Bug
但我接下來 10 幾 20 天沒辦法開發
目前應該還不影響使用及分數的準確性
所以我可能會等一段時間才會修這個 Bug

確實可以考慮增加 Check Update 的按鈕功能
Chrome 上有[這個 API](https://developer.chrome.com/docs/extensions/reference/runtime/#method-requestUpdateCheck)

**Comment by 1chooo** [comment]
@cliffxzx 
Hi!!!
非常感謝您的回覆，若有需求需要幫忙，可以直接與我討論，或說有那裡我可以直接幫忙修改，我也可以協助發 PRs。

**Comment by 1chooo** [comment]
若有修正這個 bug `README.md` 的範例圖示也可以一併更改。

**Comment by cliffxzx** [comment]
Fixed on [v0.1.1](https://github.com/cliffxzx/gpa-calculator-for-ncu/releases/tag/v0.1.1)

**Comment by 1chooo** [comment]
Thanks! 想問現在版本要如何更新，是直接刪除重新下載嗎？

**Comment by 1chooo** [comment]
另外 `README.md` 的說明圖是也可以一起修正！
